tests:
  # Here goes a list of tests you are ready to run.
  # It is expected to be a YAML sequence of strings.
  #- cmp
  #- primes
  #- matrix
  #- ndarray
  #- maxqueue
  #- vector
  #- firstn
  #- nthelement
  #- radix
  #- bitset
  #- treebalanced
  #- treeinorder
  #- treesym
  #- treenoleft
  #- treeserialise
  #- lru
  - fulltext
